SELECT TOP (1000) [OrderID]
      ,[CustomerID]
      ,[EmployeeID]
      ,[OrderDate]
      ,[RequiredDate]
      ,[ShippedDate]
      ,[ShipVia]
      ,[Freight]
      ,[ShipName]
      ,[ShipAddress]
      ,[ShipCity]
      ,[ShipRegion]
      ,[ShipPostalCode]
      ,[ShipCountry]
      ,[CompanyName]
      ,[Address]
      ,[City]
      ,[Region]
      ,[PostalCode]
      ,[Country]
  FROM [Northwind].[dbo].[Orders Qry]
